RESOURCE/INI/interfaces/interfaces.ini
Automatically rescales interfaces for screen resolution (aka currently in MS)
=> Dynamic scaling for interfaces

Program/DIALOGS/russian/Common_Governor.c, Program/DIALOGS/russian/Common_Mayor.c, Program/DIALOGS/russian/Common_Prison.c, Program/DIALOGS/russian/MainHero_dialog.c, Program/DIALOGS/russian/Prison/Cumana_Prison.c, Program/DIALOGS/russian/Quest/BlackSails/ChernyeParusaNaGorizonte.c, Program/DIALOGS/russian/Quest/BlackSails/Kurtuaznye_Strasti.c, Program/DIALOGS/russian/Quest/BlackSails/Neulovimaya_Urka.c, Program/DIALOGS/russian/Quest/BlackSails/Pogonya_Nachalas.c, Program/DIALOGS/russian/RelationAgent_dialog.c, Program/INTERFACE/NationRelation.c, Program/Quests/quests_reaction.c, Program/Quests/reaction_functions.c, Program/Quests/whisper_line_functions.c, Program/scripts/Other_Quests.c, Program/scripts/smuggling.c
Now we have only 1 function to change flag from anywhere.
=> Flag Change Edit

Program/DIALOGS/russian/Common_Portman.c
Получение отношения колоний убрал ниже, т.к выдавало ошибки, при нахождении колонии "none"
=> Error Spam Fix

Program/INTERFACE/option_screen.c, Program/WorldMap/worldmap.c
Скрипты под будущий двиг, где можно настраивать флаг на глобалке.
=> Added Customise

Program/WorldMap/worldmap.c
96 выглядит лучше. Вроде бы коммит делал в ветку, но че то не то случилось, видимо
=> Width change

Program/SEA_AI/AICameras.c, Program/reload.c
Fixes Land Camera Perspective and Distance bars in options.
Still has some issues as engine is not fully compatible for that.
=> Land Camera Fix

Program/ITEMS/items_utilite.c, Program/characters/QuestsUtilite.c, Program/loc_ai/LAi_utils.c
Во время эффекта резкого удара нельзя есть еду. Теперь 2 или больше резких ударов подряд просто добавляют таймер, а не сбрасывают энергию в 0. Функция GetStrSmallRegister поправлена для работы с UTF-8
=> Fix Swift Attack

Program/INTERFACE/NationRelation.c, Program/Quests/quests_reaction.c, Program/SEA_AI/AIShip.c
Поправил КД на несменяемость флагов и видео для них. Добавил месседж для линий кораблей на будущее
=> Fixed Flags Videos

Program/scripts/PsHero.c
Вернул авторелоад после захвата последнего корабля в Предложении Пирата (морской вариант)
=> Autoreload for PGG_Q1

Program/DIALOGS/russian/PGG_dialog.c, Program/DIALOGS/russian/pgg_dialog_town.c, Program/characters/CharacterUtilite.c
Should fix wrong PGG companion joining
=> Companions Fix

Program/INTERFACE/items.c
=> Infinite Weight Throwaway Fix

Program/DIALOGS/russian/Smuggler_Guards_dialog.c
=> Smuggler Trade Fix

Program/seadogs.c
Исключает активацию берсерка в небоевом режиме.
=> Only allow to enable berserk in a fight mode

Program/characters/init/StoryCharacters.c
Использование новой модельки для Уицилопочтли.
=> Use new model for Uicilopochtli

Program/loc_ai/LAi_utils.c
More info here: […s/storm-engine/issues/104](https://github.com/storm-devs/storm-engine/issues/104)
=> fix for Blood questline

Program/DIALOGS/russian/Shipyard/Pirates_Shipyard.c, Program/INTERFACE/ship.c, RESOURCE/INI/texts/russian/Hulls.txt
Починка Летучего Голландца с заменой модели на новую от Ноктуса.
=> Implement Flying Dutchman repair

Program/INTERFACE/option_screen.c, Program/Locations/init/boarding.c, Program/battle_interface/ispyglass.c, Program/loc_ai/LAi_boarding.c
Косметки в подзоной трубе
Фиксы лоадингов
Мелкие фиксы интерфейсов
=> Мелкофиксы

Program/INTERFACE/option_screen.c
- remove fullscreen requirement for gamma/brightness/contrast
- fix slider-to-gamma calculation
=> Fix gamma stuff

Program/CANNONS/Cannons_init.c, Program/SEA_AI/AIBalls.c, Program/SEA_AI/AICannon.c, Program/SEA_AI/AIShip.c, Program/scripts/ShipsUtilites.c
- дальность крупнокалиберных пушек снижена, чтобы не задевать игрока с "безопасного" расстояния
- увеличена минимальная точность, уменьшена максимальная.
- теперь больше снарядов летит в центр и меньше по краям
- разброс сделан чуть более вертикальным чем горизонтальным
- навыки игрока влияют на скорость залпа вдвое слабее, изначальная скорость залпа увеличена на треть
- уменьшено влияние на дальность от восприятия и перков - было слишком большое
- уменьшена погрешность авто-наводки
- теперь крит от бомбы всегда сопровождается взрывом.
=> фиксы артиллерии

Program/Quests/reaction_functions.c, Program/SEA_AI/shipWalk.c, Program/battle_interface/BattleInterface.c, Program/scripts/ShipsUtilites.c
-Теперь на палубах:
Будут солдаты если ГГ с патентом или на военных/универсальных кораблях непиратской нации
Будет сброд если корабль торговый, ГГ без патента или у пиратов
=> Нац Матросы на палубах

Program/Addons/GenerateQuests.c, Program/NumberUtilities.c, Program/scripts/time_events.c
Фикс генераторного квеста "Дуэлянт"
=> Fix for generator quest

Program/DIALOGS/russian/Mayor/Santiago_Mayor.c
нужны ещё исправленные локаторы Nikk'а
=> Исправление осады Ла Веги по испанской линейке

Program/DIALOGS/russian/Quest/MainheroPrologues/Mary_dialog.c
- Исправление проблемы с заставкой после кекса с Мэри.
=> Исправление кекса с Мэри

Program/DIALOGS/russian/Common_Brothel.c, Program/DIALOGS/russian/FencingTownHead_dialog.c, Program/loc_ai/LAi_monsters.c
- "Девица" в джунглях
- Необычное свидание в борделе
- Самый преданный фанат
=> Easter Egg Disable

Program/INTERFACE/transfer_main.c
Теперь не должен превращать офицеров в пленников и дублировать. Нужно тестировать.
=> Правка скролла в интерфейсе обмена кораблями

Program/DIALOGS/russian/Common_Portman.c, Program/DIALOGS/russian/Common_Shipyard.c
показ в диалогах, при выборе кого назначить капитаном нового корабля (забираемого из ПУ или заказного), списка офицеров с занимаемыми должностями
=> Add fan idea show job in dialog before making companion

Program/DIALOGS/russian/Common_Shipyard.c, Program/INTERFACE/shipyard1.c, Program/INTERFACE/shipyard2.c
Fix нет роста навыка корабела выше 100 и уменьшение числа бермудок на 1 (56..58 - 0 тюнингов, 59..76 - 1, 77..94 - 2, 95..100 - 3)
=> Fix нет роста навыка корабела выше 100 и уменьшение числа бермудок на 1

Program/CANNONS/Cannons_init.c, Program/SEA_AI/AIBalls.c, Program/SEA_AI/AICannon.c, Program/SEA_AI/AIShip.c, Program/STORE/initGoods.c, Program/battle_interface/utils.c
- для пушек сделана более пологая траектория - ядрам, картечи и бомбам(только при авто-прицеливании)
- временно изменена высота наводки по кораблям
=> правки настильности артиллерии

Program/DIALOGS/russian/Soldier/Nassau_Soldier.c, Program/INTERFACE/MapBest.c, Program/Locations/init/Bahames.c, Program/Locations/init/StLucia.c, Program/Locations/init/boarding.c, Program/Locations/locations_init.c, Program/STORE/store.h, Program/STORE/store_init.c, Program/WorldMap/worldmap_init.c, Program/battle_interface/fast_reload_table.c, Program/battle_interface/reload_tables.c, Program/characters/TravelMap.c, Program/characters/characters_init.c, Program/characters/init/Bahames.c, Program/colonies/Colonies_init.c, Program/globals.c, Program/islands/Islands_init.c, RESOURCE/INI/texts/russian/LocLables.txt
Доработать, чтобы все чуваки в своих лавках были
=> Добавлены багамы и город Нассау (надо доработаать кодерам)

Program/SEA_AI/AIBalls.c, Program/SEA_AI/AIFantom.c
- изменено дефолтное снаряжение кораблей - добавлены доски, парусина, снаряды и порох; количество оружия и лекарств теперь примерно равно количеству матросов.
=> дефолтное снаряжение кораблей

Program/DIALOGS/russian/Mayor/Jackman.c, Program/DIALOGS/russian/Mayor/LeFransua_Mayor.c, Program/DIALOGS/russian/Quest/MagicCity.c, Program/DIALOGS/russian/Quest/Morgan.c, Program/DIALOGS/russian/Tavern/PortoBello_Tavern.c, Program/Quests/reaction_functions.c, Program/Quests/whisper_line_functions.c
Ибо нехуй. А то с текущим ребалансом они таких пиздов давать будут. А некоторые наоборот - не будут.
=> Баланс квестовых кораблей

Program/Dialog_func.c, Program/INTERFACE/MapBest.c, Program/INTERFACE/mapview.c, Program/Locations/init/Bahames.c, RESOURCE/INI/texts/russian/common.ini
Добавил недостающие лейблы, реализовал телепортацию
=> Доработка кода Багам

Program/characters/GeneratorUtilite.c, Program/characters/RPGUtilite.c, Program/scripts/officers.c
Приводило к исключению (рассчитанное количество умений было больше необходимого)
=> Исправление логики расчета умений при ускорении.

Program/INTERFACE/perks/perks.c, Program/scripts/utils.c
возможно, исправит смену характера у ПГГ при ПП. 
Но без точного указания, в какой момент это происходит, ничего не угадаешь
=> фикс - блокировка выдачи двух характеров одновременно

Program/Addons/GenerateQuests.c
https://discord.com/channels/772863144691105816/772864185713426462/1027580242522554438
Фикс этой херни, оказывается если убить посыльного капитана, потом сагрить их и съебать не добивая, то игра считала что мы все еще идем по доброму пути. По приезду в любой город, мы локались на диалог от персонажа которого уже не существует.
@VVV101 чинил когда-то, но недочинил
=> Фикс лока ГГ после ухода от корабля потерпевшего шторм

Program/SEA_AI/AICannon.c
Сейчас точно не сломаются, на кораблекрушенцах вылетов нет.
=> Починил пушки нормально

Program/Addons/utils.c, Program/DIALOGS/russian/MainHero_dialog.c, Program/DIALOGS/russian/Quest/MainheroPrologues/Prologue_Undead_dialog.c, Program/DIALOGS/russian/Quest/T102_dialog.c, Program/INTERFACE/character.c, Program/INTERFACE/selectCharacter.c, Program/Quests/quests_reaction.c, Program/loc_ai/LAi_fightparams.c, Program/reload.c, Program/scripts/PsHero.c, RESOURCE/INI/texts/russian/HeroDescribe.txt
- Новые костюмы для Весёлого Роджера.
- Специальная модель для перерождения, у которой тоже свои костюмы.
- Ужасный убран из ПГГ, и теперь он будет только офицером для Весёлого Роджера.
=> Новые костюмы для Весёлого Роджера

Program/loc_ai/LAi_login.c
https://discord.com/channels/772863144691105816/772864185713426462/1028290568142467132
Отсутствовал локатор goto1 для локации. Переделал так чтобы антилазутчик спавнился на первом доступном локаторе.
=> Фикс лазутчика и блока выхода из локации

Program/scripts/time_events.c
-Теперь в ежесуточном методе лечения офицеров и ГГ будут сниматься знаки крит эффектов. 
-Теперь перебор всех НПС в методе обучения капитула не будет осуществляться до отдачи приказа на постройку Капитула
=> Фиксы и оптимизация таймивентов

Program/characters/CharacterUtilite.c
- для перерождённой модели нежити добавлена проверка мушкета
=> Фикс перерождённого

Program/Weather/WhrSeaPresets.c
https://discord.com/channels/772863144691105816/772864185713426462/1028770599436292147
@iNoctus перепроверь погоду на такие вот места.
=> Фикс погоды и бага с иисусом в ГПК

Program/DIALOGS/russian/Usurer_dialog.c
Если есть квест по поиску нищих, он перезаписывает возможность отказаться от поиска камня.ш
=> Usurer fix

Program/Addons/GenerateQuests.c, Program/DIALOGS/russian/GenerateQuestDuel_dialog.c, Program/DIALOGS/russian/Quest/PDM/Proklyataya_Jara.c, Program/Quests/quests_reaction.c, Program/Quests/reaction_functions.c, Program/characters/QuestsUtilite.c
- Исправлен баг с попыткой задать вопрос квестовому солдату.
- Играя за нежить в квесте "Чудесное спасение на рифах" теперь за нас будут сражаться скелеты вместо матросов.
- Генераторный квест "Дуэлянт" был улучшен.
https://user-images.githubusercontent.com/80119294/194919312-1edfccae-e96d-4420-a597-edb64079c8ae.mp4
=> Улучшенный Дуэлянт

Program/characters/GeneratorUtilite.c, Program/seadogs.c
Требует НИ для уже сгенерированных
Также добавил в метод НИ очистку персонажей. В теории должно убрать зависания при повторных НИ.
=> Фикс характеров квестовиков

Program/INTERFACE/perks/perks.c
This reverts commit 8118f1fe3841469fefd68fbb9c57e44f85a5017a.
Отревертил фикс бестредусера, ломал таймеры берса (возможно и корабельных тоже, не проверял)
=> Revert "фикс отваливания таймера"

Program/INTERFACE/character_all.h, Program/INTERFACE/itemsbox.c, Program/characters/QuestsUtilite.c
Теперь все повторяющиеся кусочки карты будут автоматически заменяться на недостающие
=> Замена кусочков карты на недостающие

Program/Addons/Arena.c, Program/Addons/GenerateQuests.c, Program/DIALOGS/russian/Mayor/Jackman.c, Program/DIALOGS/russian/Quest/Berglars.c, Program/DIALOGS/russian/RelationAgent_dialog.c, Program/ITEMS/itemLogic.c, Program/Quests/quests_reaction.c, Program/Quests/reaction_functions.c, Program/characters/LSC_Q2Utilite.c, Program/characters/QuestsUtilite.c, Program/loc_ai/LAi_login.c, Program/scripts/Treasure.c, Program/scripts/bountyhunters.c
теперь там вместо бутылочно-сломанной анимации будут обычные анимки ловкачей, что в целом более играбельно, но всё же еще сложно
=> Хардкорные анимации

Program/ITEMS/initItems.c, Program/characters/CharacterUtilite.c, Program/loc_ai/LAi_fightparams.c
=> Добавил конкретику для логов

Program/INTERFACE/shipyard1.c, Program/INTERFACE/shipyard2.c
забыл, что теперь может быть 0 тюнингов при низком навыке корабела. :(
=> фикс - запрет тюнинга при заказе корабля, если он должен быть недоступен

Program/DIALOGS/russian/Common_poorman.c, Program/INTERFACE/items.c
Не тестировалось и вопрос в том, обязателен ли диалог с нищим? ничего не сломается, если уплыть на остров, не поговорим с ним.
=> фикс - запись в журнал после прочтения письма с Траста

Program/scripts/companions.c
Reverts xxxLEOPARDxxx/CSP_Thander#231
=> Revert "Lock companion boarding interface due to particles crash"

Program/Quests/mainhero_prologues_functions.c
Исправлен захват Санто-Доминго с суши. Испанские солдаты теперь не будут спавниться на стенах.
=> Фикс Санто-Доминго

Program/INTERFACE/ship.c, Program/characters/CharacterUtilite.c
Также добавил возможность сортировать по любому атрибуту, не только по скорости. В дальнейшем можно реализовать для этого подходящий интерфейс.
=> Отрефакторил код сортировки компаньонов

Program/INTERFACE/character_all.c, Program/INTERFACE/character_all.h, Program/INTERFACE/items.c
фикс отображения в скролле персонажей пустых слотов абордажников при их снятии с должности
=> Qwerry st patch only one empty fighter slot

Program/DIALOGS/russian/Common_Portman.c, Program/DIALOGS/russian/PGG_dialog.c, Program/DIALOGS/russian/Quest/ForAll_dialog.c, Program/INTERFACE/interface.c, Program/INTERFACE/mapview.c
Сделал правку в interface.c по аналогии с ККС. Не знаю даёт ли что-либо.
Расширил диапазон для телепортации по картам для Куманы.
=> Перегенерация ПП если лока закрыта для квестов + микроправки

Program/DIALOGS/russian/Enc_Officer_dialog.c, Program/INTERFACE/items.c, Program/INTERFACE/option_sl.c, Program/INTERFACE/save_load.c, Program/scripts/utils.c
Перед вливанием стоит всё проверить
=> Всякие фиксы

Program/INTERFACE/items.c, Program/INTERFACE/utilite.c, RESOURCE/INI/fonts_rus.ini, RESOURCE/INI/interfaces/itemsbox.ini, RESOURCE/INI/interfaces/itemstrade.ini
- Впилил версию мода на отображение эффектов ХО в описаниях от EvgAnat. Кредитсы Медовому барсуку за первую реализацию тоже. Требуется файл ресурсов из мода для корректной работы.
- Впилил код на отображение картографического атласа первым объектом в разделе карт в предметах.
=> Впилил 2 мода

Program/scripts/CompanionTravel.c
=> Поправил вылет с отправкой компаньонов

Program/DIALOGS/russian/Quest/Ascold.c, Program/DIALOGS/russian/Quest/Berglars.c, Program/ITEMS/itemLogic.c, Program/Quests/reaction_functions.c, Program/loc_ai/LAi_location.c
блокируем появление Проклятого Кэпа при Остинцах и Лейфе Эриксоне
=> Cursed cap

Program/SEA_AI/AIBalls.c
вдвое реже и вдвое меньше урона
=> фикс - уменьшение урона пушек от самоподрыва примерно в 4 раза

Program/SEA_AI/AIBalls.c, Program/SEA_AI/AICannon.c
This reverts commit 299da8cd563414f3d1f030f8478b7e1b5407ce6e.
=> Revert "kek"

Program/loc_ai/LAi_types.c, RESOURCE/animation/mushketer.ani, RESOURCE/animation/mushketer_whisper.ani, RESOURCE/animation/mushketer_whisper_short.ani
Хз насколько правильно настроены анимации, но вроде всё работает. Требуются an файлы с https://discord.com/channels/772863144691105816/772863145164144672/1045321330561654836, переименованные соответственно.
За анимации выражаем благодарность Antix#9031.
=> Мушкетёры теперь могут сидеть в таверне

Program/DIALOGS/russian/Quest/ForAll_dialog.c, Program/Quests/quests_reaction.c
- Исправлен критический баг
- Была уменьшена денежная награда
=> Генераторки (Пря и Лат)

Program/scripts/GenQuests.c
фикс - при смерти на пути к городу - лочит ГГ после входа в город
=> фикс-смерть девки в джунглях

Program/scripts/GoldFleet.c
1. галеоны в середину построения, убрал рандомный 6 галеон.
2. заменил Алексисы на УсилФрегат, так как Алексис не испанский.
3. немного исправил загрузку военных снарядами. 
надеюсь не сломал ничего.  (
=> ЗФ - немного переделал

Program/characters/LSC_Q2Utilite.c, Program/scripts/Other_Quests.c, Program/scripts/ShipsUtilites.c
+ корабли засады не ниже 5 ранга.
на люггерах и баркасах глупо охотиться на флейт.
=> фикс_правильный калибр пушек у засады по квесту Орион

Program/DIALOGS/russian/Common_Duel.c, Program/DIALOGS/russian/Quest/WhisperLine/Whisper_PGG.c, Program/DIALOGS/russian/pgg_dialog_town.c, Program/scripts/officers.c
Теперь предлагает квест после найма в качестве офицера. Требования ранга снижено с 30 до 15.
=> Доработка виспер

Program/INTERFACE/PsHero.c, Program/INTERFACE/interface_utils.c, Program/INTERFACE/itemsbox.c, Program/INTERFACE/itemstrade.c, Program/INTERFACE/ship.c, Program/INTERFACE/shipyard.c, Program/INTERFACE/shipyard1.c, Program/INTERFACE/shipyard2.c, Program/INTERFACE/storage.c, Program/INTERFACE/store.c, Program/INTERFACE/transfer_main.c
починена сортировка текста
добавлена визуальная индикация
=> сортировка таблиц v2.0

Program/battle_interface/BattleInterface.c, Program/battle_interface/utils.c
Требуется тестирование. Вроде бы, работает даже без НИ. 
Как-то подозрительно легко.
Вообще непонятно, зачем этот код, если вы новые картинки не к конец файла добавляете, а в середину, смещая все затронутые.
=> фикс - укорачиваем длинный перечень кораблей в батлинтерфейсе

Program/Locations/locations_loader.c, Program/OnLoadReinit.c, Program/SEA_AI/AIFantom.c, Program/SEA_AI/AIShip.c, Program/SEA_AI/sea.c, Program/characters/characters.c, Program/characters/characters_ai.c, Program/characters/characters_init.c, Program/characters/characters_login.c, Program/characters/init/Other.c, Program/globals.c, Program/loc_ai/LAi_init.c, Program/loc_ai/LAi_login.c, Program/loc_ai/LAi_utils.c, Program/scripts/MerchantOnMap.c, Program/scripts/ShipsUtilites.c, Program/scripts/utils.c, Program/seadogs.c
Требует тестов, не мерджить до полной уверенности.
=> ЭКСПЕРИМЕНТАЛЬНО Пересобрал правки фантомов

Program/loc_ai/LAi_events.c
Механика идеального блока как на MS.
Принцип такой, что можно отбить неотразимый удар, если ставить блок в установленный тайминг.
Требует правки в движке поэтому пока не мерджить.
=> Идеальный блок (пока не мерджить)

Program/Locations/init/Jamaica.c, Program/Locations/init/PuertoPrincipe.c, Program/Weather/WhrSea.c
Фикс перехода в банк Форт Оранж, добавлены пальмы в новом Пуэрто-принсипе, фикс черной полосы в море
=> Фиксы локации море(требуют НИ и ресурсы)

RESOURCE/INI/aliases/music_alias.ini
Ресурсы не забыть
https://discord.com/channels/772863144691105816/772923073162510358/1063048051058561054
=> Добавил ванильную тему из ГПК

Program/INTERFACE/TavernWait.c, RESOURCE/INI/interfaces/TavernWait.ini, RESOURCE/INI/texts/russian/common.ini
Теперь можно перематывать и минуты, а также теперь при точной перемотке видно итоговое время. 
Пока ещё требует доработки, не все вопросы решены.
=> Доработки меню перемотки времени

Program/DIALOGS/russian/Common_church.c, Program/loc_ai/LAi_events.c
Фикс квеста по Сплавать забрать книжки. Некорректно работало с Мейном
=> Dialog Fix

Program/loc_ai/LAi_character.c
Теперь после стана офицеры не убирают саблю в ножны
=> Фикс стана

Program/Quests/quests.c, Program/Quests/quests_reaction.c
Поправил функцию с ОЗГ и сделал лог о не найденном персонаже ЛогТест
=> Fix Error Log

Program/Weather/WhrSea.c, Program/Weather/WhrSeaPresets.c, Program/Weather/WhrUtils.c, Program/Weather/WhrWeather.c, Program/Weather/init/Day.c, Program/Weather/init/DayStorm.c, Program/Weather/init/Evening.c, Program/Weather/init/Morning.c, Program/Weather/init/Night.c, Program/Weather/init/Rain.c, Program/Weather/init/Special.c
Фикс выхода из гпк не было шторма и ГГ бегал по воздуху, плейн моря и туманы, изменил диапазоны ветров чтобы все пресеты использовались в игре, динамик волна и прочие мелкие доработки. В папке текстур пена изменить название текстуры "pena1" на "pena" и заменить
=> Фиксы_доработка_море_погода

Program/loc_ai/types/LAi_citizen.c
- Теперь матросы будут обладать своим синим значком над головой и НЕ БУДУТ приставать на улице.
НО! Если знаки над головой выключены, то приставать БУДУТ.
=> У матросов синий значок

Program/DIALOGS/russian/Usurer_dialog.c, Program/Quests/mainhero_prologues_functions.c
- Генераторка "Поиск драгоценного камня" теперь выдаётся в отдельной ветке про работу у ростовщика.
=> Поиск драгоценного камня в отдельной ветке

Program/Addons/utils.c, Program/DIALOGS/russian/MainHero_dialog.c, Program/DIALOGS/russian/Quest/WhisperLine/Whisper.c, Program/Locations/init/QuestLocations.c, Program/Quests/whisper_line_functions.c, Program/characters/RPGUtilite.c
- переделана вступительная часть в подземелье пролога Виспер.
=> Киберпанк2077

Program/INTERFACE/transfer_main.c, RESOURCE/INI/interfaces/questbook.ini, RESOURCE/INI/interfaces/questbook_alt.ini, RESOURCE/INI/interfaces/shipyard.ini, RESOURCE/INI/interfaces/transfer_main.ini
-Добавлена возможность перекладывать товар с корабля на корабль указав нужное количество -Правка отображения команды в Квестбуке (Корабли в ПУ).
=> Правки из закрепов

Program/INTERFACE/MapBest.c, Program/STORE/StoreUtilite.c
-Фикс контрабанды динамической торговли
=> Фикс динамической торговли

Program/Quests/quests_reaction.c
- Исправление зависания диалога в Латыни, если не успеть ответить.
=> Исправление Латыни

Program/DIALOGS/russian/Common_church.c, Program/Quests/mainhero_prologues_functions.c, Program/Quests/quests_reaction.c
- если играть за Анжелику Тич, то у вас будут заблокированы генераторные квесты в джунглях, теперь это поправлено. (если не хотите начинать новую игру, то поговорите со священником, он вам разблокирует генераторные квесты в джунглях)
=> Анжелика в пустых джунглях

Program/DIALOGS/russian/Mayor/Jackman.c, Program/INTERFACE/game_menu.c
- исправлен визуальный баг с неправильным отображением урона по ГГ.
=> Исправление опечаток в тексте

Program/DIALOGS/russian/Quest/SilencePrice/Luke.c
- исправлен баг ПРИ ПОВТОРНОМ ВОЗВРАЩЕНИИ В ЛА ВЕГУ АНЖЕЛИКИ ТИЧ ПРИ ПОВТОРНОМ ОБРАЩЕНИИ К  ЛЮКУ ФРАЙЛЕНГУ
=> Исправлен баг с Анжеликой и Люком

Program/DIALOGS/russian/Mayor/Jackman.c
- Исправлен баг с началом 6 квеста Пиратской Линейки
=> Исправлен баг с началом 6 квеста Пиратской Линейки

Program/Quests/whisper_line_functions.c
- Исправлен баг с Виспер, который не позволял выбрать нацию у дипломата
=> Исправлен баг с Виспер, который не позволял выбрать нацию у дипломата
